### ISSUE TITLE
[question: alphacross] how to import .puz files?

### ISSUE THREAD

**Issue by warren-bank** [pokebyte/ararat#12]
Hi. Sorry to bother you. I just installed [alphacross v1.96](https://play.google.com/store/apps/details?id=org.akop.crosswords). So far, it looks perfect.. exactly what I wanted. I do have one question though. The description says that it can import external puzzles in .puz (Across Lite) file format.. but I don't see any UI that would allow me to do so. I was hoping that you would be so kind as to quickly explain how to do so.

ex:
* Should they be added to one of the directories under: `/data/data/org.akop.crosswords/`?
* Is there a way to read them directly off of an external SD card?

Much thanks!

**Comment by pokebyte** [comment]
For issues with the app, please contact me via email at the Play listing - don't create GH issues.

To import any .puz file to alphacross, open the file in Android. This can be done by downloading it via web, opening it as an attachment in an email, or opening it via a file browser app.
