### ISSUE TITLE
Not able to import some .puz files

### ISSUE THREAD

**Issue by markclowes** [pokebyte/ararat#8]
http://www.private-eye.co.uk/pictures/crossword/download/?O=D

Attempting to import a few of the puzzles from the top of the above URL into Alphacross 1.80 results in some failures. I presume they are Across Lite compliant.

Works:
586
590

Doesn't: (Import failed - format not recognised)
585
587
588
591

**Comment by pokebyte** [comment]
Thanks for reporting! From what I can tell, the solutions to those puzzles are scrambled, with no possible key to unscramble them. Maybe I need to consider the possibility of crosswords with no known solutions.

**Comment by pokebyte** [comment]
It looks like the puzzles don't have an embedded solution - something the library isn't able to deal with at the moment.

**Comment by markclowes** [comment]
Thanks for investigating! There is a cash prize involved with these particular puzzles, so including solutions would indeed be detrimental.
